/* Insight dashboard — client rendering.
 *
 * Plain DOM, no framework, no build step. It reads two files:
 *   data.json     generated by analyze.mjs — everything measured from the tree
 *   backlog.json  hand-maintained — the judgement calls, edit it directly
 *
 * Every number on screen traces to a file and line in data.json. Nothing here
 * infers, estimates or rounds; if a figure looks wrong the analyzer is wrong, and
 * tools/insight/verify.mjs is where that gets pinned down.
 */
'use strict';

const el = (tag, attrs = {}, ...kids) => {
  const n = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (k === 'class') n.className = v;
    else if (k === 'html') n.innerHTML = v;
    else if (k.startsWith('on')) n.addEventListener(k.slice(2), v);
    else if (v !== null && v !== undefined && v !== false) n.setAttribute(k, v);
  }
  for (const kid of kids.flat()) {
    if (kid === null || kid === undefined || kid === false) continue;
    n.appendChild(typeof kid === 'object' ? kid : document.createTextNode(String(kid)));
  }
  return n;
};

const num = (n) => n.toLocaleString('en-US');
const view = document.getElementById('view');

let DATA = null;
let BACKLOG = null;

/* ── shared bits ───────────────────────────────────────────────────────── */
function cards(list) {
  return el('div', { class: 'cards' }, list.map(([n, l, cls]) =>
    el('div', { class: 'card' + (cls ? ' ' + cls : '') },
      el('div', { class: 'n' }, typeof n === 'number' ? num(n) : n),
      el('div', { class: 'l' }, l))));
}

function table(head, rows, opts = {}) {
  if (!rows.length) return el('div', { class: 'wrap' }, el('div', { class: 'empty' }, opts.empty || 'Nothing here.'));
  return el('div', { class: 'wrap' },
    el('div', { class: 'scroll' },
      el('table',
        {},
        el('thead', {}, el('tr', {}, head.map((h) => el('th', { class: typeof h === 'object' && h.num ? 'num' : '' }, typeof h === 'object' ? h.label : h)))),
        el('tbody', {}, rows))));
}

/* A file:line reference. Not a link — nothing here can open an editor reliably —
   but click copies it, which is what you actually do with one. */
function ref(path, line) {
  const text = line ? `${path}:${line}` : path;
  return el('code', {
    class: 'mono',
    title: 'click to copy',
    style: 'cursor:pointer',
    onclick: (e) => {
      navigator.clipboard?.writeText(text);
      const t = e.target;
      const was = t.textContent;
      t.textContent = 'copied';
      setTimeout(() => { t.textContent = was; }, 700);
    },
  }, text);
}

function filterBox(placeholder, onInput) {
  const input = el('input', { type: 'search', placeholder, oninput: (e) => onInput(e.target.value.toLowerCase().trim()) });
  return input;
}

/* ── 1. Relations ──────────────────────────────────────────────────────── */
function pageRelations() {
  const d = DATA;
  const wrap = el('div', {});
  wrap.append(
    el('h1', {}, 'Relations'),
    el('p', { class: 'lede' },
      'Every entry point, what it renders, and what styles it pulls in. Thirty-one hand-written HTML shells each '
      + 'name one page module; that module imports shared components from src/components and one stylesheet, which '
      + '@imports the rest of the design system. This is the whole chain, resolved.'),
    cards([
      [d.totals.viteEntries, 'page entries'],
      [d.totals.modules, 'JS modules'],
      [num(d.totals.moduleLoc) + '', 'lines of JS'],
      [d.totals.sharedComponents, 'shared components'],
      [d.totals.cssFiles, 'stylesheets'],
      [num(d.totals.cssLoc) + '', 'lines of CSS'],
    ]),
  );

  /* shared components by fan-in — the blast-radius table */
  wrap.append(
    el('h2', {}, 'Shared components, by how many files import them'),
    el('p', { class: 'note' },
      'The top of this list is the blast radius: change one of these and every importing page changes with it. '
      + 'Expand a row for the exact importers and for per-export usage — a file can hold a live component and an orphaned one.'),
  );

  const maxFan = Math.max(1, ...d.sharedComponents.map((c) => c.importedBy.length));
  const compHost = el('div', {});
  const renderComps = (q = '') => {
    compHost.textContent = '';
    const list = d.sharedComponents.filter((c) => !q || c.path.toLowerCase().includes(q) || c.exports.join(' ').toLowerCase().includes(q));
    for (const c of list) {
      const deadExports = c.exportUsage.filter((e) => e.dead);
      compHost.append(el('details', {},
        el('summary', {},
          el('span', { class: 'grow' }, ref(c.path)),
          el('span', { class: 'tag' + (c.importedBy.length ? ' teal' : ' bad') }, c.importedBy.length + ' importers'),
          deadExports.length ? el('span', { class: 'tag warn' }, deadExports.length + ' unused export' + (deadExports.length > 1 ? 's' : '')) : null,
          el('span', { class: 'tag flat' }, num(c.loc) + ' loc'),
          el('span', { class: 'bar', style: `width:${Math.round((c.importedBy.length / maxFan) * 120)}px` })),
        el('div', { class: 'body' },
          el('div', {}, el('strong', {}, 'Imported by'), c.importedBy.length ? null : ' — nobody'),
          el('ul', {}, c.importedBy.map((p) => el('li', {}, ref(p)))),
          el('div', {}, el('strong', {}, 'Exports')),
          el('ul', {}, c.exportUsage.map((e) => el('li', {},
            el('code', { class: 'mono' }, e.name),
            ' ',
            e.dead
              ? el('span', { class: 'tag warn' }, e.liveUsers.length ? 'reached only from dead code' : 'never used')
              : el('span', { class: 'tag good' }, e.liveUsers.length + ' live user' + (e.liveUsers.length === 1 ? '' : 's')),
            ' ',
            el('span', { class: 'tag flat' }, e.lines + ' loc'))))),
      ));
    }
    if (!list.length) compHost.append(el('div', { class: 'empty' }, 'No component matches.'));
  };
  wrap.append(el('div', { class: 'tools' }, filterBox('Filter components or exports…', renderComps)), compHost);
  renderComps();

  /* pages */
  wrap.append(
    el('h2', {}, 'Pages'),
    el('p', { class: 'note' },
      'Shell → module → shared components. "Local components" are defined inside the page file itself rather than shared; '
      + 'a high count there is what the Combine tab is about.'),
  );
  const pageHost = el('div', {});
  const renderPages = (q = '') => {
    pageHost.textContent = '';
    const rows = d.pages
      .filter((p) => !q || p.shell.toLowerCase().includes(q) || (p.title || '').toLowerCase().includes(q))
      .map((p) => el('tr', {},
        el('td', {}, ref(p.shell)),
        el('td', {}, p.module ? ref(p.module) : el('span', { class: 'tag bad' }, 'no module')),
        el('td', { class: 'num' }, num(p.moduleLoc)),
        el('td', { class: 'num' }, p.sharedComponents.length),
        el('td', { class: 'num' }, p.localComponents),
        el('td', {}, p.deadLocalComponents.length
          ? el('span', { class: 'tag warn' }, `${p.deadLocalComponents.length} dead · ${num(p.deadLocalLines)} loc`)
          : el('span', { class: 'tag flat' }, '—')),
        el('td', {}, p.robots && /noindex/.test(p.robots) ? el('span', { class: 'tag' }, 'noindex') : '',
          p.inPrerender ? '' : el('span', { class: 'tag bad' }, 'not prerendered'),
          p.todos.length ? el('span', { class: 'tag warn', title: p.todos.join('\n') }, p.todos.length + ' TODO') : null)));
    pageHost.append(table(
      ['Shell', 'Module', { label: 'JS loc', num: true }, { label: 'Shared', num: true }, { label: 'Local', num: true }, 'Dead local', 'Flags'],
      rows,
    ));
  };
  wrap.append(el('div', { class: 'tools' }, filterBox('Filter pages…', renderPages)), pageHost);
  renderPages();

  /* css chain */
  wrap.append(
    el('h2', {}, 'Stylesheets'),
    el('p', { class: 'note' },
      'Reached means: linked from a shell, imported by a live module, or @imported by a stylesheet that is itself reached. '
      + 'Anything under public/ is copied verbatim into dist/, so an unreached file there still ships.'),
  );
  const cssRows = d.cssFiles
    .slice()
    .sort((a, b) => (a.reachable === b.reachable ? b.loc - a.loc : a.reachable ? 1 : -1))
    .map((c) => el('tr', {},
      el('td', {}, ref(c.path)),
      el('td', { class: 'num' }, num(c.loc)),
      el('td', { class: 'num' }, c.rules),
      el('td', { class: 'num' }, c.classCount),
      el('td', { class: 'num' }, c.unusedClasses.length
        ? el('span', { class: 'tag warn', title: c.unusedClasses.slice(0, 40).join('\n') }, String(c.unusedClasses.length))
        : el('span', { class: 'tag flat' }, '0')),
      el('td', {}, c.reachable
        ? el('span', { class: 'tag good', title: c.roots.join('\n') }, c.roots.length ? c.roots[0] : 'via @import')
        : el('span', { class: 'tag bad' }, c.shipsAnyway ? 'orphan — but ships' : 'orphan')),
    ));
  wrap.append(table(['Stylesheet', { label: 'loc', num: true }, { label: 'rules', num: true }, { label: 'classes', num: true }, { label: 'unused', num: true }, 'Reached via'], cssRows));

  return wrap;
}

/* ── 2. Not used ───────────────────────────────────────────────────────── */
function pageUnused() {
  const d = DATA;
  const wrap = el('div', {});
  const reclaimable = d.totals.deadModuleLoc + d.totals.deadSymbolLines + d.totals.orphanCssLoc;

  wrap.append(
    el('h1', {}, 'Not used'),
    el('p', { class: 'lede' },
      'Reachability from the thirty-one entry points, following imports AND JSX element usage. That second part is why '
      + 'this list is short enough to act on: an import graph alone cannot tell a rendered component from an orphaned '
      + 'one, because <Hero /> is neither a call nor an import.'),
    cards([
      [reclaimable, 'lines reclaimable', 'hot'],
      [d.deadModules.length, 'unreachable files'],
      [d.deadSymbols.length, 'unused components'],
      [d.orphanCss.length, 'orphaned stylesheets'],
      [d.totals.duplicateWastedLoc, 'duplicated lines', 'bad'],
    ]),
  );

  wrap.append(el('h2', {}, 'Files nothing imports'));
  wrap.append(table(['File', { label: 'loc', num: true }, 'Note'],
    d.deadModules.map((m) => el('tr', {},
      el('td', {}, ref(m.path)),
      el('td', { class: 'num' }, num(m.loc)),
      el('td', {}, m.shipsAnyway ? el('span', { class: 'tag bad' }, 'under public/ — ships to production anyway') : el('span', { class: 'tag flat' }, 'not built')))),
    { empty: 'Every file is reachable.' }));

  wrap.append(el('h2', {}, 'Byte-identical duplicates'));
  wrap.append(el('p', { class: 'note' }, 'Same SHA-256. One of each group is redundant.'));
  wrap.append(table(['Copies', { label: 'loc each', num: true }, { label: 'wasted', num: true }],
    d.duplicateFiles.map((g) => el('tr', {},
      el('td', {}, g.map((f) => el('div', {}, ref(f.path)))),
      el('td', { class: 'num' }, num(g[0].loc)),
      el('td', { class: 'num' }, el('span', { class: 'tag bad' }, num(g[0].loc * (g.length - 1)))))),
    { empty: 'No duplicated files.' }));

  wrap.append(el('h2', {}, 'Components never rendered'));
  wrap.append(el('p', { class: 'note' },
    '"Reached only from dead code" means the component is not independently removable but falls out for free once its '
    + 'parent goes — so deleting one thing can reclaim far more than its own line count. Sorted by size.'));

  const symHost = el('div', {});
  let onlyBig = false;
  const renderSyms = (q = '') => {
    symHost.textContent = '';
    const rows = d.deadSymbols
      .filter((s) => !onlyBig || s.lines >= 50)
      .filter((s) => !q || s.file.toLowerCase().includes(q) || s.name.toLowerCase().includes(q))
      .map((s) => el('tr', {},
        el('td', {}, el('code', { class: 'mono' }, s.name)),
        el('td', {}, ref(s.file, s.line)),
        el('td', { class: 'num' }, s.lines),
        el('td', {}, s.referencedBy.length
          ? el('span', { class: 'tag warn', title: s.referencedBy.join('\n') }, 'reached only from dead code')
          : el('span', { class: 'tag bad' }, 'never referenced')),
        el('td', {}, s.exported ? el('span', { class: 'tag' }, 'exported') : '')));
    symHost.append(table(['Component', 'Defined at', { label: 'loc', num: true }, 'Why it is dead', ''], rows));
  };
  const bigBtn = el('button', {
    class: 'chip',
    onclick: (e) => { onlyBig = !onlyBig; e.target.classList.toggle('on', onlyBig); renderSyms(searchSym.value.toLowerCase().trim()); },
  }, '50+ lines only');
  const searchSym = filterBox('Filter components…', renderSyms);
  wrap.append(el('div', { class: 'tools' }, searchSym, bigBtn), symHost);
  renderSyms();

  wrap.append(el('h2', {}, 'Orphaned stylesheets'));
  wrap.append(table(['Stylesheet', { label: 'loc', num: true }, 'Note'],
    d.orphanCss.map((c) => el('tr', {},
      el('td', {}, ref(c.path)),
      el('td', { class: 'num' }, num(c.loc)),
      el('td', {}, c.shipsAnyway ? el('span', { class: 'tag bad' }, 'ships to production') : el('span', { class: 'tag flat' }, 'not built')))),
    { empty: 'Every stylesheet is reached.' }));

  wrap.append(el('h2', {}, 'Class names defined but never mentioned'));
  wrap.append(el('p', { class: 'note' },
    'Read this as a shortlist, not a verdict. Usage is collected from EVERY string literal in the repo, which '
    + `over-counts on purpose — ${num(d.totals.dynamicClassStrings)} strings build class names by interpolation `
    + '(`ins-connector-logo ${slug}`), and a name assembled at runtime cannot be proved unused by reading source. '
    + 'Check a candidate in the browser before deleting it.'));
  wrap.append(table(['Stylesheet', { label: 'unused', num: true }, { label: 'of', num: true }, 'Examples'],
    d.cssFiles.filter((c) => c.unusedClasses.length).sort((a, b) => b.unusedClasses.length - a.unusedClasses.length).slice(0, 40)
      .map((c) => el('tr', {},
        el('td', {}, ref(c.path)),
        el('td', { class: 'num' }, c.unusedClasses.length),
        el('td', { class: 'num' }, c.classCount),
        el('td', {}, el('code', { class: 'mono', style: 'color:var(--faint)' }, c.unusedClasses.slice(0, 6).join(', ') + (c.unusedClasses.length > 6 ? ' …' : ''))))),
    { empty: 'Every declared class name appears somewhere.' }));

  return wrap;
}

/* ── 3. Combine ────────────────────────────────────────────────────────── */
function pageCombine() {
  const d = DATA;
  const wrap = el('div', {});
  const identical = d.repeated.filter((r) => r.sameStructure);
  const variants = d.repeated.filter((r) => !r.sameStructure);

  wrap.append(
    el('h1', {}, 'Combine'),
    el('p', { class: 'lede' },
      'Component names defined in more than one file. Bodies are hashed after whitespace normalisation, so "identical" '
      + 'means the code really is the same and the copies can be replaced by one import today. Variants need a prop or '
      + 'two to absorb the differences — a bigger job, and usually the bigger prize.'),
    cards([
      [identical.length, 'names sharing a structure'],
      [d.totals.savableByConsolidation, 'lines liftable to props', 'hot'],
      [variants.length, 'names with variants'],
      [variants.reduce((a, r) => a + r.totalLines, 0), 'lines in variants'],
    ]),
  );

  const groupTable = (list, title, note) => {
    const host = el('div', {});
    host.append(el('h2', {}, title), el('p', { class: 'note' }, note));
    for (const r of list) {
      host.append(el('details', {},
        el('summary', {},
          el('span', { class: 'grow' }, el('code', { class: 'mono' }, r.name)),
          el('span', { class: 'tag' + (r.identical ? ' good' : ' warn') },
            r.sameStructure ? (r.sameCode ? `${r.copies} identical copies` : `${r.copies} copies, same shape, different copy`) : `${r.copies} copies / ${r.distinctBodies} distinct`),
          el('span', { class: 'tag flat' }, `${num(r.totalLines)} loc total`),
          r.identical ? el('span', { class: 'tag teal' }, `−${num(r.savableLines)} loc`) : null,
          r.alreadySharedAs ? el('span', { class: 'tag teal' }, 'already shared') : null),
        el('div', { class: 'body' },
          r.alreadySharedAs
            ? el('div', {}, 'A shared version already exists at ', ref(r.alreadySharedAs), ' — the page-local copies can import it.')
            : null,
          el('ul', {}, r.where.map((w) => el('li', {}, ref(w.file, w.line), ' ',
            el('span', { class: 'tag flat' }, w.lines + ' loc'), ' ',
            el('span', { class: 'tag flat', style: 'color:var(--faint)' }, w.hash)))),
          r.identical
            ? null
            : el('div', { style: 'color:var(--faint);margin-top:6px' },
              `${r.distinctBodies} distinct bodies — the hashes above show which copies match each other. `
              + 'Start with any two that share a hash.')),
      ));
    }
    return host;
  };

  wrap.append(groupTable(identical, 'Same structure — one shared component, copy as props',
    'The JSX shape is identical once string literals are set aside. Where the copy matches too — tagged "identical copies" '
    + 'below — the duplicates can simply go. Otherwise the words lift into props and the shell is shared.'));
  wrap.append(groupTable(variants.filter((r) => r.copies >= 3), 'Variants — same idea, drifted',
    'These have diverged. The line counts say how much is at stake; the hashes say which copies are still in step with each other.'));

  return wrap;
}

/* ── 4. Health ─────────────────────────────────────────────────────────── */
function pageHealth() {
  const d = DATA;
  const wrap = el('div', {});
  const routeHoles = d.routeMatrix.filter((r) => !(r.vite && r.serve && r.apiDir && r.client));
  const envHoles = d.envMatrix.filter((e) => !e.inCompose || !e.inEnvExample);

  wrap.append(
    el('h1', {}, 'Health'),
    el('p', { class: 'lede' },
      'The wiring that has actually broken production. Both waitlist outages were this: the route was registered in '
      + 'vite.config.js but not in server/serve.js, so it 404\'d in the container; then the endpoint read '
      + 'ZOHO_WAITLIST_FORM_URL which docker-compose.yml did not pass, so it 503\'d. Unit tests passed and the build was '
      + 'clean both times. These two tables are the check that was missing.'),
    cards([
      [routeHoles.length, 'route holes', routeHoles.length ? 'bad' : 'ok'],
      [envHoles.length, 'env holes', envHoles.length ? 'hot' : 'ok'],
      [d.entryDrift.inViteNotPrerender.length + d.entryDrift.inPrerenderNotVite.length, 'entry-map drift', 'ok'],
      [d.parseWarnings.length, 'files parsed with doubt', d.parseWarnings.length ? 'hot' : 'ok'],
    ]),
  );

  const yes = (b) => b ? el('span', { class: 'tag good' }, 'yes') : el('span', { class: 'tag bad' }, 'MISSING');

  wrap.append(el('h2', {}, 'Every /api route must appear in four places'));
  wrap.append(table(['Route', 'vite.config.js', 'server/serve.js', 'api/*.js', 'client fetch'],
    d.routeMatrix.map((r) => el('tr', {},
      el('td', {}, el('code', { class: 'mono' }, r.route)),
      el('td', {}, yes(r.vite)), el('td', {}, yes(r.serve)), el('td', {}, yes(r.apiDir)), el('td', {}, yes(r.client))))));

  wrap.append(el('h2', {}, 'Every env var the server reads must be passed to the container'));
  wrap.append(el('p', { class: 'note' },
    'A missing docker-compose entry is a silent 503 on one form while the others work. '
    + '.env.example is documentation only — a gap there costs the next person an hour, not an outage.'));
  wrap.append(table(['Variable', 'read by', 'docker-compose.yml', '.env.example', '.gitlab-ci.yml'],
    d.envMatrix.map((e) => el('tr', {},
      el('td', {}, el('code', { class: 'mono' }, e.name)),
      el('td', {}, e.readBy.map((p) => el('div', {}, ref(p)))),
      el('td', {}, yes(e.inCompose)), el('td', {}, yes(e.inEnvExample)), el('td', {}, yes(e.inCi))))));

  wrap.append(el('h2', {}, 'Entry maps'));
  wrap.append(el('p', { class: 'note' },
    'vite.config.js and scripts/prerender.mjs each hold the same list of 31 entries, by hand. A page in one and not the '
    + 'other either never builds or never gets prerendered — and the prerenderer warns and exits 0, so nothing fails.'));
  const drift = [...d.entryDrift.inViteNotPrerender.map((e) => [e, 'in vite.config.js, not in prerender.mjs']),
    ...d.entryDrift.inPrerenderNotVite.map((e) => [e, 'in prerender.mjs, not in vite.config.js'])];
  wrap.append(table(['Entry', 'Problem'],
    drift.map(([e, why]) => el('tr', {}, el('td', {}, ref(e)), el('td', {}, el('span', { class: 'tag bad' }, why)))),
    { empty: 'Both maps list the same 31 entries.' }));

  wrap.append(el('h2', {}, 'Analyzer self-doubt'));
  wrap.append(el('p', { class: 'note' },
    'Files whose braces do not balance after strings, comments and regex literals are blanked. The blanker mis-parsed '
    + 'something, so spans — and therefore dead-code claims — in these files are not trustworthy. Published rather than hidden.'));
  wrap.append(table(['File', 'Brace delta'],
    d.parseWarnings.map((w) => el('tr', {}, el('td', {}, ref(w.path)), el('td', {}, el('span', { class: 'tag warn' }, String(w.braceDelta))))),
    { empty: 'Every file parsed cleanly — brace-balanced after blanking.' }));

  return wrap;
}

/* ── 5. Actions & ideas ────────────────────────────────────────────────── */
function pageActions() {
  const b = BACKLOG;
  const wrap = el('div', {});
  if (!b) {
    wrap.append(el('h1', {}, 'Actions & ideas'), el('p', { class: 'empty' }, 'backlog.json is missing.'));
    return wrap;
  }

  const items = b.items.slice();
  const open = items.filter((i) => i.status !== 'done');
  const byImpact = (s) => ({ high: 0, medium: 1, low: 2 }[s] ?? 3);
  const byEffort = (s) => ({ trivial: 0, small: 1, medium: 2, large: 3 }[s] ?? 4);
  items.sort((a, b2) => (a.status === 'done') - (b2.status === 'done')
    || byImpact(a.impact) - byImpact(b2.impact)
    || byEffort(a.effort) - byEffort(b2.effort));

  const cats = [...new Set(items.map((i) => i.category))].sort();

  wrap.append(
    el('h1', {}, 'Actions & ideas'),
    el('p', { class: 'lede' }, b.intro),
    cards([
      [open.length, 'open'],
      [open.filter((i) => i.impact === 'high').length, 'high impact', 'hot'],
      [open.filter((i) => i.effort === 'trivial' || i.effort === 'small').length, 'quick wins', 'ok'],
      [open.filter((i) => i.blocked_on).length, 'blocked'],
      [items.filter((i) => i.status === 'done').length, 'done', 'ok'],
    ]),
    el('p', { class: 'note' },
      'This file is hand-maintained: tools/insight/backlog.json. Edit it directly — set "status": "done" to strike an '
      + 'item through, add items as they come up. It is deliberately not generated, because the judgement about what is '
      + 'worth doing is not something static analysis has an opinion on.'),
  );

  let cat = '';
  let quick = false;
  const host = el('div', {});
  const render = (q = '') => {
    host.textContent = '';
    const list = items.filter((i) =>
      (!cat || i.category === cat)
      && (!quick || i.effort === 'trivial' || i.effort === 'small')
      && (!q || (i.title + ' ' + i.detail + ' ' + i.evidence).toLowerCase().includes(q)));
    for (const i of list) {
      host.append(el('div', { class: 'item' + (i.status === 'done' ? ' done' : '') },
        el('div', { class: 'head' },
          el('span', { class: 'title' }, i.title),
          el('span', { class: 'tag' }, i.category),
          el('span', { class: 'tag ' + (i.impact === 'high' ? 'bad' : i.impact === 'medium' ? 'warn' : 'flat') }, i.impact + ' impact'),
          el('span', { class: 'tag' }, i.effort),
          i.blocked_on ? el('span', { class: 'tag warn' }, 'blocked: ' + i.blocked_on) : null,
          i.status === 'done' ? el('span', { class: 'tag good' }, 'done') : null),
        el('p', { class: 'detail' }, i.detail),
        i.evidence ? el('div', { class: 'ev' }, i.evidence) : null));
    }
    if (!list.length) host.append(el('div', { class: 'empty' }, 'Nothing matches.'));
  };

  const search = filterBox('Search actions…', render);
  const select = el('select', { onchange: (e) => { cat = e.target.value; render(search.value.toLowerCase().trim()); } },
    el('option', { value: '' }, 'All categories'), cats.map((c) => el('option', { value: c }, c)));
  const quickBtn = el('button', {
    class: 'chip',
    onclick: (e) => { quick = !quick; e.target.classList.toggle('on', quick); render(search.value.toLowerCase().trim()); },
  }, 'Quick wins only');
  wrap.append(el('div', { class: 'tools' }, search, select, quickBtn), host);
  render();

  /* Non-goals and sequencing. Kept on the same page as the work rather than in a
     separate document, because the value of "we looked at this and decided not
     to" evaporates the moment it is somewhere nobody reads — and without it the
     next pass re-derives the same analysis and reaches the same answer. */
  if (b.notes && b.notes.length) {
    wrap.append(
      el('h2', {}, 'Decided against, corrected, and sequencing'),
      el('p', { class: 'note' },
        'Conclusions that are not tasks: work that looked worthwhile and is not, claims that turned out to be wrong, '
        + 'and the order in which some of these items make each other cheaper.'),
      el('div', {}, b.notes.map((n) => el('div', { class: 'item' }, el('p', { class: 'detail', style: 'margin:0' }, n)))),
    );
  }
  return wrap;
}

/* ── routing ───────────────────────────────────────────────────────────── */
const PAGES = {
  relations: pageRelations,
  unused: pageUnused,
  combine: pageCombine,
  health: pageHealth,
  actions: pageActions,
};

function route() {
  const name = (location.hash.replace('#/', '') || 'relations');
  const fn = PAGES[name] || PAGES.relations;
  for (const a of document.querySelectorAll('.tabs a')) a.classList.toggle('on', a.dataset.tab === name);
  view.textContent = '';
  try {
    view.append(fn());
  } catch (err) {
    view.append(el('div', { class: 'empty' }, 'Failed to render: ' + err.message));
    console.error(err);
  }
  window.scrollTo(0, 0);
}

async function boot() {
  try {
    const [d, b] = await Promise.all([
      fetch('/data.json', { cache: 'no-store' }).then((r) => r.json()),
      fetch('/backlog.json', { cache: 'no-store' }).then((r) => (r.ok ? r.json() : null)).catch(() => null),
    ]);
    DATA = d;
    BACKLOG = b;
  } catch (err) {
    view.textContent = '';
    view.append(el('div', { class: 'empty' }, 'Could not load data.json — run `npm run insight:build` first. (' + err.message + ')'));
    return;
  }

  const when = new Date(DATA.totals.generatedAt);
  document.getElementById('stamp').textContent = `${DATA.totals.modules} modules · ${DATA.totals.cssFiles} stylesheets · analysed ${when.toLocaleString()}`;

  const reclaim = DATA.totals.deadModuleLoc + DATA.totals.deadSymbolLines + DATA.totals.orphanCssLoc;
  const set = (id, text, cls) => {
    const n = document.getElementById(id);
    n.textContent = text;
    if (cls) n.className = 'pill ' + cls;
  };
  set('pill-unused', num(reclaim), 'warn');
  set('pill-combine', num(DATA.totals.savableByConsolidation), 'warn');
  const holes = DATA.totals.routeHoles + DATA.totals.envHoles + DATA.parseWarnings.length;
  set('pill-health', String(holes), holes ? 'bad' : 'good');
  if (BACKLOG) set('pill-actions', String(BACKLOG.items.filter((i) => i.status !== 'done').length));

  if (DATA.parseWarnings.length) {
    document.getElementById('foot-warn').textContent = `${DATA.parseWarnings.length} file(s) parsed with doubt — see Health`;
  }

  window.addEventListener('hashchange', route);
  route();
}

boot();
